services:
  db:
    image: postgres:latest
    container_name: ordens-de-servicos-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Pass@123
      POSTGRES_DB: ordens-de-servicos-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - postgres

volumes:
  postgres_data:

networks:
  postgres:
    driver: bridge
